spring:
  datasource:
    url: ENC(n4/vfuXi9RgGDgM4YDTlAwr+l5NODha2ZOeXaQgOSasKRiz7J1MCGFhnNQ8ZoA0mgpmSLtbeN3HnvPS0D5L/1u9NZpmjcU1Ta6P6nP1aY84abBrIc4aL0UwW84IpznW4)
    username: ENC(oBxGv0XAqduP8hmdbBo95g==)
    password: ENC(bCUkpOfQtjd7mb4OJiuJytIyxuIqjuK/)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB # 파일 하나당 크기
      max-request-size: 20MB # 전송하려는 총 파일 크기

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(AP1O1srqv0Kq7nLQaEp8xZHKRwPcy9EqHnCyFzYIGVWadI0zLKszdU4GLji8/GWMSf8n0EKg5qZyWbHDzQ8T2WD/05l09vhXAVI0MTokGs7Vq4LJlSUGyw==)
            client-secret: ENC(ptIkZSfqr7Fby7HyyYFv1w9VD7zeO4F9KShBxbLDSo1A7V/VsPnf+ibrFMvUr9dw)
            redirect-uri: https://main.d2tymbwxxoagk6.amplifyapp.com/login/google
            scope:
              - email

cloud:
  aws:
    credentials:
      accessKey: ENC(ovlMiS3z8h4ibksrBpL1LTJIvDhaVUK88zQtSMYIkDw=)
      secretKey: ENC(Xcox3M12b78LKg7nyEvHAVfJv586pGXDuNszoTXOdop5bJFWCiNwQSsJxJtgV5WGN/3yTGxlLUw=)
    s3:
      bucket: weneedbucket/files
    region:
      static: ap-northeast-2
    stack:
      auto: false
jwt:
  issuer: ENC(bbdtWueEsh7LW+PrGzB46UwfJKBJW8DMJcbn9cAkLrk=)
  secret_key: ENC(3P9HeDamaRYl9h4zz9M7Vy7xoQZ23d4t)

univcertKey: ENC(qv85ftlYv6nJRP/yWbWsLuFbZCsNQVzoHAs5ioRaG0StCAWs7XaPq8qiYvqkDte6)