spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weneed
    username: root
    password: ENC(jyZNNshW4DfvjG9sSLZeIMMheMSCaWat)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      #valicate로 바꾸기
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
jwt:
  issuer: ENC(bbdtWueEsh7LW+PrGzB46UwfJKBJW8DMJcbn9cAkLrk=)
  secret_key: ENC(3P9HeDamaRYl9h4zz9M7Vy7xoQZ23d4t)